FROM fedora:40 as build

RUN dnf -y update \
 && dnf -y install \
        rustup \
        git \
        jq \
 && dnf clean all
 
RUN git clone https://github.com/zed-industries/zed.git /app
WORKDIR /app

RUN rustup-init -y \
 && source "$HOME/.cargo/env" \
 && script/linux \
 && dnf clean all \
 && script/bundle-linux \
 && cp /app/target/release/zed-*-linux-x86_64.tar.gz /app/zed.tar.gz

FROM fedora:40

WORKDIR /app
COPY --from=build /app/zed.tar.gz /app/

